name: 'Smoketest for Lyrion Music Server'
on:
  push:
  workflow_dispatch:
  pull_request_target:
    types: [assigned, labeled]
jobs:
  linux:
    name: Run LMS to see whether it crashes immediately...
    runs-on: ubuntu-22.04

    steps:
      - name: Make sure we're running as non-root
        run: |
          if [ "$RUNNER_USER" == "root" ]; then
            echo Specify non-root image when testing with act:
            echo act -P ubuntu-22.04=ghcr.io/catthehacker/ubuntu:runner-22.04
            exit 1
          fi

      - uses: actions/checkout@v4

      - name: Install depedencies
        run: |
          if [ "$ACT" == "true" ]; then
            sudo apt-get update
          fi
          sudo apt-get install -y libio-socket-ssl-perl libnet-ssleay-perl netcat

      - name: Run test
        run: bash t/00_smoketest.sh
